# Generated by Django 4.0.5 on 2023-06-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
